"""Validation for the per-field evidence schema (SITE-1).

Source of truth: ingest/site_sources.yaml + ingest/sites/<site_id>.yaml.
ingest/sites.geojson is generated by ingest/build_sites.py; these tests keep
the generator honest and the generated file in sync.
"""
import json
import sys
from pathlib import Path

import pytest
import yaml

REPO = Path(__file__).resolve().parents[1]
INGEST = REPO / "ingest"

CATEGORIES = {"excavation_report", "excavation_project", "peer_reviewed",
              "unesco", "gazetteer", "course_material", "official_record",
              "expert_statement"}
KINDS = {"source", "normalized", "derived", "provisional", "na"}
STATES = {"verified", "unverified"}
AFFILIATIONS = {"harappan", "related"}
FIELDS = ["name", "coordinates", "periods", "size_class",
          "excavation_status", "notes", "harappan_connection"]


@pytest.fixture(scope="module")
def registry():
    return yaml.safe_load((INGEST / "site_sources.yaml").read_text())["sources"]


@pytest.fixture(scope="module")
def site_docs():
    docs = {}
    for path in sorted((INGEST / "sites").glob("*.yaml")):
        docs[path.stem] = yaml.safe_load(path.read_text())
    return docs


def test_registry_valid(registry):
    assert registry, "source registry is empty"
    for sid, src in registry.items():
        assert src["category"] in CATEGORIES, f"{sid}: bad category"
        assert src["citation"].strip(), f"{sid}: empty citation"
        assert isinstance(src.get("artifacts", []), list)


def test_site_files_complete(site_docs):
    assert len(site_docs) >= 10
    for site_id, doc in site_docs.items():
        assert doc["site_id"] == site_id
        assert doc["affiliation"] in AFFILIATIONS
        assert list(doc["fields"]) == FIELDS, f"{site_id}: field order/names"


def test_field_kinds_states(site_docs):
    for site_id, doc in site_docs.items():
        for fname, f in doc["fields"].items():
            assert f["kind"] in KINDS, f"{site_id}.{fname}: bad kind"
            assert f["state"] in STATES, f"{site_id}.{fname}: bad state"
            assert isinstance(f.get("evidence", []), list)


def test_verified_fields_have_evidence(site_docs, registry):
    for site_id, doc in site_docs.items():
        for fname, f in doc["fields"].items():
            if f["kind"] == "na":
                continue
            if f["state"] == "verified":
                ev = f.get("evidence", [])
                assert ev, f"{site_id}.{fname}: verified but no evidence"
                for e in ev:
                    assert e["source"] in registry, \
                        f"{site_id}.{fname}: unregistered source {e['source']}"
                    assert e["locator"].strip(), \
                        f"{site_id}.{fname}: empty locator"
            else:  # unverified: must be an explicit provisional claim
                assert f["kind"] == "provisional", \
                    f"{site_id}.{fname}: unverified must be kind=provisional"


def test_coordinates_sane(site_docs):
    for site_id, doc in site_docs.items():
        c = doc["fields"]["coordinates"]
        lon, lat = c["value"]
        assert -180 <= lon <= 180 and -90 <= lat <= 90, \
            f"{site_id}: coordinates out of range"
        assert c["uncertainty_m"] > 0, f"{site_id}: bad uncertainty_m"
        assert c.get("method", "").strip(), f"{site_id}: no derivation method"


def test_generated_geojson_in_sync(site_docs, registry):
    sys.path.insert(0, str(INGEST))
    import build_sites
    importlib_reload = __import__("importlib").reload
    importlib_reload(build_sites)
    expected = {"type": "FeatureCollection", "features":
                [build_sites.build_feature(d, registry)
                 for d in sorted(site_docs.values(),
                                 key=lambda d: d["site_id"])]}
    actual = json.loads((INGEST / "sites.geojson").read_text())
    assert actual == expected, \
        "ingest/sites.geojson is stale - rerun ingest/build_sites.py"


def test_review_status_derived(site_docs):
    fc = json.loads((INGEST / "sites.geojson").read_text())
    by_id = {f["properties"]["site_id"]: f["properties"] for f in fc["features"]}
    for site_id, doc in site_docs.items():
        states = [f["state"] for f in doc["fields"].values()]
        expected = ("verified" if all(s == "verified" for s in states)
                    else "partial" if any(s == "verified" for s in states)
                    else "unverified")
        assert by_id[site_id]["review_status"] == expected, site_id
    assert by_id["kalibangan"]["review_status"] == "partial"
    # map/API compatibility keys survived the rebuild
    for pid, p in by_id.items():
        for key in ("name", "affiliation", "periods", "size_class",
                    "excavation_status", "notes", "uncertainty_m",
                    "sources", "coordinate_provenance", "authority_note"):
            assert key in p, f"{pid}: missing {key}"
