"""
Georeferencing for Vats 1940, Plate I (site plan of Harappa).

The plan was rendered from the 1999 ASI reprint scan
(data/artifacts/plates-source.pdf, PDF p.11) at 300 dpi (1749x1241 px).
Pixel coordinates below are NORMALIZED 0-1000 (x = px/1749*1000, y = px/1241*1000).

Transform: similarity (scale + rotation + translation), plan pixels -> WGS-84.

  Scale:    1.2595 m/px, measured from the plan's 1000-ft survey grid
            (E1000-E5000 ticks on the neatline average 242 px per 1000 ft;
             304.8 m / 242 px).  NOTE: the plan's printed 400-yard scale bar
            measures ~402 px, which disagrees (~0.91 m/px); the survey grid
            agrees with GPS control points to 8%, so the grid is trusted and
            the scale-bar discrepancy is recorded, not used.
  Rotation: true north lies 2.96 deg east of image-up, measured from the
            plan's north arrow shaft (linear fit, 571 pts).
  Anchor:   the MUSEUM building. OSM "Harappa Museum" building centroid
            (30.6247339, 72.8646927) matched to the museum symbol on the plan
            at normalized (480, 829).

Validation: the Harappa village built-up core on the plan, transformed,
lands 155 m from the OSM village node (30.6330564, 72.8701682), almost
entirely in longitude -- consistent with the modern village having grown
eastward since 1940.  Transform accuracy is therefore estimated at
~100-200 m, which is fit for MOUND-level (not trench-level) provenance.

Uncertainty model: every georeferenced place carries a provenience level
and an uncertainty radius.  A seal's location is "somewhere within this
place" -- never an exact excavation coordinate.

Provenience levels (standard archaeological findspot hierarchy, coarsest
to finest; cf. CIDOC CRM E53 Place with P89 "falls within" nesting):

    site  - the settlement as a whole (Harappa)
    area  - a named subdivision: mound, area, or operation (Mound F, "Mound P"
            = the Great Granary complex).  This is what Vats' tabulation
            column "Mound or Area" records.
    square - an excavation grid square (Vats' 100-ft squares, e.g. "Square J").
            The tabulation does not give squares; Vats Vol I text sometimes
            does ("Square J 9/20").  Not yet parsed -- reserved for future.
    locus - a stratigraphic context within a square.  Not in the tabulation.
    point - an exact 3D coordinate.  Not recoverable from this publication.

A record's location always references the FINEST place level actually known
from the source, with the place's polygon as the footprint and its centroid
as the representative point for distance queries.
"""

import json
import math
import os

# --- provenience hierarchy --------------------------------------------------
# Standard archaeological levels, coarsest -> finest.  A place's id encodes
# its ancestry: "harappa:area:F" falls within "harappa" (cf. CIDOC CRM P89).
LEVELS = ("site", "area", "square", "locus", "point")
SITE_ID = "harappa"
SITE_CENTER = (30.62919, 72.86444)  # mean of area centroids, WGS-84

# --- transform parameters -------------------------------------------------
IMG_W, IMG_H = 1749, 1241          # render size the normalized coords refer to
M_PER_PX = 304.8 / 242.0           # 1000-ft grid cell measured at 242 px
THETA = math.radians(2.96)         # north is this far EAST of image-up
ANCHOR_PX = (0.480 * IMG_W, 0.829 * IMG_H)   # museum symbol, plan pixels
ANCHOR_LL = (30.6247339, 72.8646927)         # museum, WGS-84 (OSM building)

COS_T, SIN_T = math.cos(THETA), math.sin(THETA)

# --- public API -------------------------------------------------------------
def plan_px_to_wgs84(x_px, y_px):
    """Plan pixel coords (1749x1241 space) -> (lat, lon)."""
    u = x_px - ANCHOR_PX[0]
    v = y_px - ANCHOR_PX[1]
    east_m = (u * COS_T + v * SIN_T) * M_PER_PX
    north_m = (u * SIN_T - v * COS_T) * M_PER_PX
    lat = ANCHOR_LL[0] + north_m / 110540.0
    lon = ANCHOR_LL[1] + east_m / (111320.0 * math.cos(math.radians(ANCHOR_LL[0])))
    return lat, lon


def norm_to_wgs84(xn, yn):
    """Normalized 0-1000 plan coords -> (lat, lon)."""
    return plan_px_to_wgs84(xn / 1000.0 * IMG_W, yn / 1000.0 * IMG_H)


def polygon_centroid(poly):
    """Planar centroid of a polygon in normalized coords."""
    xs = [p[0] for p in poly]
    ys = [p[1] for p in poly]
    return sum(xs) / len(xs), sum(ys) / len(ys)


def load_areas_geojson(path=None):
    """Load the WGS-84 mound areas GeoJSON (generated by build_areas())."""
    if path is None:
        path = os.path.join(os.path.dirname(__file__), "mound_areas.geojson")
    with open(path) as f:
        return json.load(f)


def build_areas(pixels_path=None, out_path=None):
    """Transform hand-traced plan polygons to WGS-84 GeoJSON."""
    if pixels_path is None:
        pixels_path = os.path.join(os.path.dirname(__file__), "mound_areas_pixels.json")
    if out_path is None:
        out_path = os.path.join(os.path.dirname(__file__), "mound_areas.geojson")
    with open(pixels_path) as f:
        src = json.load(f)

    features = []
    for key, area in src["areas"].items():
        poly = area["polygon"]
        ring = [norm_to_wgs84(x, y)[::-1] for x, y in poly]  # GeoJSON: [lon, lat]
        ring.append(ring[0])
        cx, cy = polygon_centroid(poly)
        clat, clon = norm_to_wgs84(cx, cy)
        features.append({
            "type": "Feature",
            "properties": {
                "place_id": f"{SITE_ID}:area:{key}",
                "level": "area",
                "parent_id": SITE_ID,
                "label": area["label"],
                "note": area["note"],
                "centroid": [clon, clat],
                "source": "Vats 1940, Pl. I (1999 ASI reprint scan)",
                "georef_method": "1000-ft grid scale + north-arrow rotation + OSM museum anchor",
                "uncertainty_m": 250,
            },
            "geometry": {"type": "Polygon", "coordinates": [ring]},
        })

    # The site itself is the root place; records whose tabulation value has
    # no mapped area fall back to it.
    features.append({
        "type": "Feature",
        "properties": {
            "place_id": SITE_ID,
            "level": "site",
            "parent_id": None,
            "label": "Harappa",
            "note": "Archaeological site; fallback for records with no mapped area",
            "centroid": [SITE_CENTER[1], SITE_CENTER[0]],
            "source": "Vats 1940, Pl. I (1999 ASI reprint scan)",
            "georef_method": "mean of area centroids",
            "uncertainty_m": 1500,
        },
        "geometry": None,
    })

    fc = {
        "type": "FeatureCollection",
        "properties": {
            "crs": "WGS-84",
            "generated_by": "ingest/georef.py build_areas()",
            "anchor": {"label": "Harappa Museum (OSM building)", "lat": ANCHOR_LL[0], "lon": ANCHOR_LL[1]},
            "scale_m_per_px": M_PER_PX,
            "rotation_deg_east_of_up": math.degrees(THETA),
            "validation": "village core within 155 m of OSM node; residual consistent with post-1940 eastward growth",
        },
        "features": features,
    }
    with open(out_path, "w") as f:
        json.dump(fc, f, indent=2)
    return out_path


if __name__ == "__main__":
    print("wrote", build_areas())
